<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\props\netcore.props" />
    <Import Project="..\..\props\common.props" />
    <Import Project="..\..\props\version.props" />

    <PropertyGroup>
        <Title>XiHan.BasicApp.AI.Tests</Title>
        <AssemblyName>XiHan.BasicApp.AI.Tests</AssemblyName>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <NoWarn>$(NoWarn);CS1591;XHFH001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\modules\XiHan.BasicApp.AI\XiHan.BasicApp.AI.csproj" />
        <ProjectReference Include="..\..\src\modules\XiHan.BasicApp.Saas\XiHan.BasicApp.Saas.csproj" />
    </ItemGroup>

</Project>
